# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b282d2cfbca74fd79a5c56d3d48eaea1c15500ba7ecc29a0c0b71ca079823fb573fb1a1cfad4e352ae7ec4d04a2f2fc76de7ee77bc2cbf64a6645721c5fa3f4c

test:
  secret_key_base: 400bf83cd14fe0b60aee7c86a09e76f8b9433f31567ca02f8cec1b1e31f13b437bd0b17379aa35f0e61386d80e34f07e2add177e2e1736ebde0d0084843d64cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
